package com.istream.ihr.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HealthPlanDtl generated by hbm2java
 */
@Entity
@Table(name = "health_plan_dtl", catalog = "ihr")
public class HealthPlanDtl implements java.io.Serializable {

	private Integer planDtlId;
	private PlanOption planOption;
	private String planType;
	private String coverageType;
	private String optionCode;
	private String planRenewMo;
	private BigDecimal montlyPremAmt;
	private Date creationTs;
	private Date lastUpdateTs;

	public HealthPlanDtl() {
	}

	public HealthPlanDtl(PlanOption planOption, String planType, String planRenewMo, BigDecimal montlyPremAmt,
			Date creationTs, Date lastUpdateTs) {
		this.planOption = planOption;
		this.planType = planType;
		this.planRenewMo = planRenewMo;
		this.montlyPremAmt = montlyPremAmt;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	public HealthPlanDtl(PlanOption planOption, String planType, String coverageType, String optionCode,
			String planRenewMo, BigDecimal montlyPremAmt, Date creationTs, Date lastUpdateTs) {
		this.planOption = planOption;
		this.planType = planType;
		this.coverageType = coverageType;
		this.optionCode = optionCode;
		this.planRenewMo = planRenewMo;
		this.montlyPremAmt = montlyPremAmt;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Plan_dtl_id", unique = true, nullable = false)
	public Integer getPlanDtlId() {
		return this.planDtlId;
	}

	public void setPlanDtlId(Integer planDtlId) {
		this.planDtlId = planDtlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Plan_opt_id", nullable = false)
	public PlanOption getPlanOption() {
		return this.planOption;
	}

	public void setPlanOption(PlanOption planOption) {
		this.planOption = planOption;
	}

	@Column(name = "Plan_type", nullable = false, length = 10)
	public String getPlanType() {
		return this.planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	@Column(name = "Coverage_type", length = 10)
	public String getCoverageType() {
		return this.coverageType;
	}

	public void setCoverageType(String coverageType) {
		this.coverageType = coverageType;
	}

	@Column(name = "Option_code", length = 10)
	public String getOptionCode() {
		return this.optionCode;
	}

	public void setOptionCode(String optionCode) {
		this.optionCode = optionCode;
	}

	@Column(name = "plan_renew_mo", nullable = false, length = 2)
	public String getPlanRenewMo() {
		return this.planRenewMo;
	}

	public void setPlanRenewMo(String planRenewMo) {
		this.planRenewMo = planRenewMo;
	}

	@Column(name = "Montly_prem_amt", nullable = false, precision = 9)
	public BigDecimal getMontlyPremAmt() {
		return this.montlyPremAmt;
	}

	public void setMontlyPremAmt(BigDecimal montlyPremAmt) {
		this.montlyPremAmt = montlyPremAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
