package com.istream.ihr.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ProjectTask generated by hbm2java
 */
@Entity
@Table(name = "project_task", catalog = "ihr")
public class ProjectTask implements java.io.Serializable {

	private Integer taskId = 1;
	private Project project = new Project();
	private String name = "tast_name";
	private Date startDate= new Date();
	private Date endDate= new Date();
	private Date creationTs= new Date();
	private Date lastUpdateTs= new Date();
	
	
	private Set<TimeSheetTaskAs> timeSheetTaskAses = new HashSet<TimeSheetTaskAs>(0);

	public ProjectTask() {
	}

	public ProjectTask(Project project, Date startDate, Date creationTs, Date lastUpdateTs) {
		this.project = project;
		this.startDate = startDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	public ProjectTask(Project project, String name, Date startDate, Date endDate, Date creationTs, Date lastUpdateTs,
			Set<TimeSheetTaskAs> timeSheetTaskAses) {
		this.project = project;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
		this.timeSheetTaskAses = timeSheetTaskAses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "task_id", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "Name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Start_Date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "End_Date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	@Transient
	public Set<TimeSheetTaskAs> getTimeSheetTaskAses() {
		return this.timeSheetTaskAses;
	}

	public void setTimeSheetTaskAses(Set<TimeSheetTaskAs> timeSheetTaskAses) {
		this.timeSheetTaskAses = timeSheetTaskAses;
	}

}
