package com.istream.ihr.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeSheet generated by hbm2java
 */
@Entity
@Table(name = "time_sheet", catalog = "ihr")
public class TimeSheet implements java.io.Serializable {

	private Integer timeSheetId;
	private Employee employee;
	private Project project;
	private Date timeSheetDate;
	private int billedHours;
	private Integer nonBilledHours;
	private String note;
	private String description;
	private String status;
	private Date creationTs;
	private Date lastUpdateTs;
	
	public TimeSheet() {
	}

	public TimeSheet(Project project, Date timeSheetDate, int billedHours, Date creationTs, Date lastUpdateTs) {
		this.project = project;
		this.timeSheetDate = timeSheetDate;
		this.billedHours = billedHours;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	public TimeSheet(Employee employee, Project project, Date timeSheetDate, int billedHours,
			Integer nonBilledHours, String note, String status, Date creationTs, Date lastUpdateTs, String description) {
		this.employee = employee;
		this.project = project;
		this.timeSheetDate = timeSheetDate;
		this.billedHours = billedHours;
		this.nonBilledHours = nonBilledHours;
		this.note = note;
		this.description = description;
		this.status = status;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Time_sheet_id", unique = true, nullable = false)
	public Integer getTimeSheetId() {
		return this.timeSheetId;
	}

	public void setTimeSheetId(Integer timeSheetId) {
		this.timeSheetId = timeSheetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Employee_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Time_sheet_date", nullable = false, length = 0)
	public Date getTimeSheetDate() {
		return timeSheetDate;
	}

	public void setTimeSheetDate(Date timeSheetDate) {
		this.timeSheetDate = timeSheetDate;
	}

	@Column(name = "Billed_Hours", nullable = false)
	public int getBilledHours() {
		return this.billedHours;
	}

	public void setBilledHours(int billedHours) {
		this.billedHours = billedHours;
	}

	@Column(name = "Non_Billed_Hours")
	public Integer getNonBilledHours() {
		return this.nonBilledHours;
	}

	public void setNonBilledHours(Integer nonBilledHours) {
		this.nonBilledHours = nonBilledHours;
	}

	@Column(name = "Note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "Description", length = 250)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	@Override
	public String toString() {
		return "TimeSheet [timeSheetId=" + timeSheetId + ", employee=" + employee + ", project=" + project
				+ ", timeSheetDate=" + timeSheetDate + ", billedHours=" + billedHours + ", nonBilledHours="
				+ nonBilledHours + ", note=" + note + ", description=" + description + ", status=" + status
				+ ", creationTs=" + creationTs + ", lastUpdateTs=" + lastUpdateTs + "]";
	}

	

}
